/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "kv.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
put_1(argp, clnt)
	KeyValue *argp;
	CLIENT *clnt;
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, PUT, xdr_KeyValue, argp, xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

GetReply *
get_1(argp, clnt)
	char **argp;
	CLIENT *clnt;
{
	static GetReply clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, GET, xdr_wrapstring, argp, xdr_GetReply, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

int *
del_1(argp, clnt)
	char **argp;
	CLIENT *clnt;
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, DEL, xdr_wrapstring, argp, xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

GetReply *
rget_1(argp, clnt)
	char **argp;
	CLIENT *clnt;
{
	static GetReply clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, RGET, xdr_wrapstring, argp, xdr_GetReply, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

PrepReply *
accept_prepare_del_1(argp, clnt)
	int *argp;
	CLIENT *clnt;
{
	static PrepReply clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, ACCEPT_PREPARE_DEL, xdr_int, argp, xdr_PrepReply, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

PrepReply *
accept_prepare_put_1(argp, clnt)
	int *argp;
	CLIENT *clnt;
{
	static PrepReply clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, ACCEPT_PREPARE_PUT, xdr_int, argp, xdr_PrepReply, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

int *
accept_execute_del_1(argp, clnt)
	char *argp;
	CLIENT *clnt;
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, ACCEPT_EXECUTE_DEL, xdr_char, argp, xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

int *
accept_execute_put_1(argp, clnt)
	KeyValue *argp;
	CLIENT *clnt;
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, ACCEPT_EXECUTE_PUT, xdr_KeyValue, argp, xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
