/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "kv.h"

bool_t
xdr_Key(xdrs, objp)
	XDR *xdrs;
	Key *objp;
{

	if (!xdr_string(xdrs, objp, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_Value(xdrs, objp)
	XDR *xdrs;
	Value *objp;
{

	if (!xdr_string(xdrs, objp, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_KeyValue(xdrs, objp)
	XDR *xdrs;
	KeyValue *objp;
{

	if (!xdr_Key(xdrs, &objp->key))
		return (FALSE);
	if (!xdr_Value(xdrs, &objp->value))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_GetReply(xdrs, objp)
	XDR *xdrs;
	GetReply *objp;
{

	if (!xdr_int(xdrs, &objp->code))
		return (FALSE);
	if (!xdr_Value(xdrs, &objp->value))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_PrepReply(xdrs, objp)
	XDR *xdrs;
	PrepReply *objp;
{

	if (!xdr_int(xdrs, &objp->vote))
		return (FALSE);
	if (!xdr_KeyValue(xdrs, &objp->kv))
		return (FALSE);
	if (!xdr_Key(xdrs, &objp->key))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->n))
		return (FALSE);
	return (TRUE);
}
